name: aeryn_salon_absen
description: AERYN SALON - Flutter attendance app (QR Check-in/Check-out).
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.3
  intl: ^0.19.0
  csv: ^5.0.2
  share_plus: ^10.0.2
